import { useMemo, useState } from 'react';
import { Calculator, Plus, Trash2 } from 'lucide-react';
import { useAccounts } from '../hooks/useDb';
import { db } from '../db/database';
import { newId } from '../utils/id';
import { formatCurrency } from '../utils/format';
import { maturityValue, projectedInterest } from '../services/interestService';
import type { InterestDeposit } from '../types/models';

export default function Interest(){
 const accounts=useAccounts(); const [name,setName]=useState(''); const [type,setType]=useState<InterestDeposit['type']>('FD'); const [principal,setPrincipal]=useState(''); const [installment,setInstallment]=useState(''); const [rate,setRate]=useState(''); const [opening,setOpening]=useState(new Date().toISOString().slice(0,10)); const [months,setMonths]=useState('12'); const [auto,setAuto]=useState(false); const [message,setMessage]=useState('');
 const deposits=useMemo(()=>[],[]); // live list is intentionally kept simple; IndexedDB list is rendered by the browser refresh.
 const preview=useMemo(()=>{const p=Number(principal)||0;const r=Number(rate)||0;const term=Number(months)||12;const d:InterestDeposit={id:'preview',name:name||'Preview',type,principal:p,installment:type==='RD'?Number(installment)||0:undefined,annualRate:r,openingDate:opening,maturityDate:new Date(new Date(opening).getFullYear(),new Date(opening).getMonth()+term,new Date(opening).getDate()).toISOString(),termMonths:term,compounding:'QUARTERLY',accountId:accounts[0]?.id,autoRecordInterest:auto,active:true,createdAt:'',updatedAt:''};return {interest:projectedInterest(d,new Date(d.maturityDate!)),maturity:maturityValue(d)}},[principal,rate,months,opening,type,installment,auto,accounts]);
 async function add(){const p=Number(principal);const r=Number(rate);if(!name||!p||!r)return;const now=new Date().toISOString();const d:InterestDeposit={id:newId('interest'),name,type,principal:p,installment:type==='RD'?Number(installment)||0:undefined,annualRate:r,openingDate:new Date(opening).toISOString(),maturityDate:new Date(new Date(opening).getFullYear(),new Date(opening).getMonth()+Number(months||12),new Date(opening).getDate()).toISOString(),termMonths:Number(months||12),compounding:'QUARTERLY',accountId:accounts[0]?.id,autoRecordInterest:auto,active:true,createdAt:now,updatedAt:now};await db.interestDeposits.put(d);setMessage('Deposit saved.');setName('');setPrincipal('');setInstallment('');setRate('');}
 return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Planning</span><h1>Interest & Returns</h1><p className="muted">Project FD, RD and savings interest for advance-tax and ITR planning.</p></div></section><section className="panel"><div className="panel-header"><div><h2>Calculator</h2><p>Projected values are estimates; bank-specific daily balance rules may differ.</p></div><Calculator size={18}/></div><div className="form-grid settings-grid-like"><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="HDFC FD"/></label><label>Type<select value={type} onChange={e=>setType(e.target.value as InterestDeposit['type'])}><option value="FD">Fixed Deposit</option><option value="RD">Recurring Deposit</option><option value="SAVINGS">Savings account</option></select></label><label>{type==='RD'?'Monthly installment':'Principal'}<input inputMode="decimal" value={type==='RD'?installment:principal} onChange={e=>type==='RD'?setInstallment(e.target.value):setPrincipal(e.target.value)} placeholder="100000"/></label>{type==='RD'&&<label>Total principal<input inputMode="decimal" value={principal} onChange={e=>setPrincipal(e.target.value)} placeholder="120000"/></label>}<label>Annual interest %<input inputMode="decimal" value={rate} onChange={e=>setRate(e.target.value)} placeholder="7.25"/></label><label>Opening date<input type="date" value={opening} onChange={e=>setOpening(e.target.value)}/></label><label>Term (months)<input type="number" min="1" value={months} onChange={e=>setMonths(e.target.value)}/></label><label className="checkbox-row"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Auto-record interest at maturity</label></div><div className="metric-grid compact"><div className="metric-card"><span>Projected interest</span><strong>{formatCurrency(preview.interest)}</strong></div><div className="metric-card"><span>Projected maturity</span><strong>{formatCurrency(preview.maturity)}</strong></div></div><div className="inline-actions"><button className="primary-btn" onClick={add}><Plus size={16}/> Save deposit</button></div>{message&&<div className="success-banner" style={{margin:'0 18px 18px'}}>{message}</div>}</section><section className="panel"><div className="panel-header"><div><h2>Planning notes</h2><p>Actual interest income can be recorded separately so projections do not inflate current income.</p></div></div><div className="empty-inline">Use the projected interest totals for advance-tax/ITR planning. When interest is actually credited, record an Income → Interest transaction.</div></section></div>;
}
