import { useState } from 'react';
import { LineChart as LineIcon, Plus, Trash2 } from 'lucide-react';
import { useAccounts, useInvestments } from '../hooks/useDb';
import { db } from '../db/database';
import { newId } from '../utils/id';
import { formatCurrency } from '../utils/format';
import { queueEntitySync } from '../services/syncService';
import { createTransaction } from '../services/transactionService';

export default function Investments() {
  const entries=useInvestments(); const accounts=useAccounts();
  const [name,setName]=useState(''); const [amount,setAmount]=useState(''); const [assetType,setAssetType]=useState<'STOCK'|'MUTUAL_FUND'|'SIP'|'FIXED_DEPOSIT'|'GOLD'|'RETIREMENT_PF'|'OTHER'>('MUTUAL_FUND'); const [type,setType]=useState<'CONTRIBUTION'|'REDEMPTION'|'DIVIDEND'|'INTEREST'>('CONTRIBUTION'); const [accountId,setAccountId]=useState('');
  async function add(){const value=Number(amount); if(!name.trim()||!value)return; const now=new Date().toISOString(); const entry={id:newId('inv'),date:now,name:name.trim(),assetType,type,amount:value,accountId:accountId||undefined,createdAt:now,updatedAt:now,syncStatus:'PENDING' as const}; await db.investments.put(entry); if(type==='CONTRIBUTION' && accountId){const investmentCategory=(await db.categories.filter(c=>c.name==='Investments'&&!c.parentId).first());const sub=(await db.categories.filter(c=>c.parentId===investmentCategory?.id&&c.name.toLowerCase().includes(assetType.toLowerCase().replace('_',' '))).first());await createTransaction({type:'EXPENSE',amount:value,transactionDateTime:now,accountId,categoryId:investmentCategory?.id,subcategoryId:sub?.id,merchant:name,notes:'Investment contribution',source:'MANUAL',sourceId:`investment:${entry.id}`});} await queueEntitySync('INVESTMENT',entry.id,'CREATE',entry); setName('');setAmount('');}
  return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Wealth</span><h1>Investments</h1><p className="muted">Track contributions and returns without mixing them into daily spending.</p></div></section>
  <section className="panel"><div className="panel-header"><div><h2>Add investment activity</h2><p>Stocks, mutual funds, SIP, FD, gold or PF.</p></div><LineIcon size={18}/></div><div className="form-grid settings-grid-like"><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="SBI Bluechip"/></label><label>Amount<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="5000"/></label><label>Asset type<select value={assetType} onChange={e=>setAssetType(e.target.value as any)}><option value="STOCK">Stocks</option><option value="MUTUAL_FUND">Mutual Fund</option><option value="SIP">SIP</option><option value="FIXED_DEPOSIT">Fixed Deposit</option><option value="GOLD">Gold</option><option value="RETIREMENT_PF">Retirement/PF</option><option value="OTHER">Other</option></select></label><label>Activity<select value={type} onChange={e=>setType(e.target.value as any)}><option value="CONTRIBUTION">Contribution</option><option value="REDEMPTION">Redemption</option><option value="DIVIDEND">Dividend</option><option value="INTEREST">Interest</option></select></label><label>Account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Optional</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><button className="primary-btn" onClick={add}><Plus size={16}/> Add activity</button></section>
  <section className="panel"><div className="panel-header"><div><h2>Recent investment activity</h2></div></div>{entries.length===0?<div className="empty-state"><div className="empty-icon">↗</div><h3>No investment records</h3><p>Add contributions or returns here.</p></div>:<div className="transaction-list">{entries.map(e=><div className="transaction-row" key={e.id}><div className="transaction-main"><strong>{e.name}</strong><span>{e.assetType.replace('_',' ')} · {e.type.toLowerCase()}</span></div><div className="transaction-meta"><time>{new Date(e.date).toLocaleDateString('en-IN')}</time><strong>{formatCurrency(e.amount)}</strong><button className="icon-btn small danger-icon" onClick={async()=>{await db.investments.delete(e.id);await queueEntitySync('INVESTMENT',e.id,'DELETE',{id:e.id});}} title="Delete"><Trash2 size={13}/></button></div></div>)}</div>}</section>
  </div>;
}
