import { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Filter, LineChart as LineIcon, Save, Trash2 } from 'lucide-react';
import { useAccounts, useCategories, useSettings, useTransactions } from '../hooks/useDb';
import { formatCurrency } from '../utils/format';
import { endOfMonth, eachMonthOfInterval, endOfYear, format, parseISO, startOfMonth, startOfYear } from 'date-fns';
import { CartesianGrid, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Cell } from 'recharts';

const colors=['#7c8cff','#5dd39e','#f2c14e','#e17878','#7fc8f8','#c39be8'];
function addMonthsKey(key:string,delta:number){const [y,m]=key.split('-').map(Number);return format(new Date(y,m-1+delta,1),'yyyy-MM');}
export default function Stats(){
 const txns=useTransactions()??[]; const cats=useCategories()??[]; const accounts=useAccounts()??[]; const settings=useSettings();
 const [yearMode,setYearMode]=useState<'MONTH'|'YEAR'>('MONTH'); const [period,setPeriod]=useState(new Date().toISOString().slice(0,7)); const [filterOpen,setFilterOpen]=useState(false); const [metric,setMetric]=useState<'AMOUNT'|'COUNT'|'PERCENT'>('AMOUNT'); const [group,setGroup]=useState<'CATEGORY'|'SUBCATEGORY'|'ACCOUNT'>('CATEGORY');
 const [categoryIds,setCategoryIds]=useState<string[]>([]); const [subcategoryIds,setSubcategoryIds]=useState<string[]>([]); const [accountIds,setAccountIds]=useState<string[]>([]); const [selectedDrill,setSelectedDrill]=useState<string>(''); const [saved,setSaved]=useState<{name:string;categoryIds:string[];subcategoryIds:string[];accountIds:string[];metric:string;group:string}[]>(()=>JSON.parse(localStorage.getItem('expense-saved-reports')||'[]'));
 const roots=cats.filter(c=>!c.parentId); const subs=cats.filter(c=>c.parentId); const selectedRootSet=new Set(categoryIds);
 const range=useMemo(()=>{if(yearMode==='MONTH'){const [y,m]=period.split('-').map(Number);const start=startOfMonth(new Date(y,m-1,1));return {start,end:endOfMonth(start)};} const [y]=period.split('-').map(Number); if(settings?.reportingYear==='FY'){const start=new Date(y,3,1);return {start,end:new Date(y+1,2,31,23,59,59,999)};} return {start:startOfYear(new Date(y,0,1)),end:endOfYear(new Date(y,0,1))};},[period,yearMode,settings?.reportingYear]);
 const rows=useMemo(()=>txns.filter(t=>t.type==='EXPENSE').filter(t=>{const d=parseISO(t.transactionDateTime);if(d<range.start||d>range.end)return false;if(categoryIds.length&&!categoryIds.includes(t.categoryId||''))return false;if(subcategoryIds.length&&!subcategoryIds.includes(t.subcategoryId||''))return false;if(accountIds.length&&!accountIds.includes(t.accountId))return false;return true;}),[txns,range,categoryIds,subcategoryIds,accountIds]);
 const total=rows.reduce((s,t)=>s+t.amount,0);
 const grouped=useMemo(()=>{const map=new Map<string,number>();for(const t of rows){const id=group==='CATEGORY'?(t.categoryId||'uncategorized'):group==='SUBCATEGORY'?(t.subcategoryId||'uncategorized'):t.accountId;map.set(id,(map.get(id)||0)+t.amount);}return [...map.entries()].sort((a,b)=>b[1]-a[1]).map(([id,amount])=>({id,name:group==='CATEGORY'?cats.find(c=>c.id===id)?.name||'Uncategorized':group==='SUBCATEGORY'?cats.find(c=>c.id===id)?.name||'Uncategorized':accounts.find(a=>a.id===id)?.name||'Unknown',amount,percent:total?amount/total*100:0}));},[rows,group,cats,accounts,total]);
 const trend=useMemo(()=>{const months=yearMode==='MONTH'?[range.start]:eachMonthOfInterval({start:range.start,end:range.end});return months.map(m=>{const end=endOfMonth(m);const monthRows=txns.filter(t=>t.type==='EXPENSE').filter(t=>{const d=parseISO(t.transactionDateTime);return d>=m&&d<=end&&(!selectedDrill||t.categoryId===selectedDrill||t.subcategoryId===selectedDrill)});const amount=monthRows.reduce((s,t)=>s+t.amount,0);return {label:format(m,'MMM'),amount,count:monthRows.length};});},[txns,range,yearMode,selectedDrill]);
 function toggle(list:string[],set:(v:string[])=>void,id:string){set(list.includes(id)?list.filter(x=>x!==id):[...list,id]);}
 function saveReport(){const name=prompt('Report name');if(!name)return;const next=[...saved,{name,categoryIds,subcategoryIds,accountIds,metric,group}];setSaved(next);localStorage.setItem('expense-saved-reports',JSON.stringify(next));}
 function clear(){setCategoryIds([]);setSubcategoryIds([]);setAccountIds([]);setSelectedDrill('');}
 return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Reports</span><h1>Stats</h1><p className="muted">Build compact reusable reports for monthly, Indian FY or calendar-year analysis.</p></div><div className="stats-actions"><button className="secondary-btn" onClick={()=>setFilterOpen(v=>!v)}><Filter size={15}/> Filters</button><button className="secondary-btn" onClick={saveReport}><Save size={15}/> Save</button></div></section>
 <section className="toolbar report-toolbar"><div className="segmented"><button className={yearMode==='MONTH'?'active':''} onClick={()=>setYearMode('MONTH')}>Monthly</button><button className={yearMode==='YEAR'?'active':''} onClick={()=>setYearMode('YEAR')}>Yearly</button></div><button className="icon-btn" onClick={()=>setPeriod(yearMode==='MONTH'?addMonthsKey(period,-1):String(Number(period.split('-')[0])-1))}><ChevronLeft/></button><strong className="period-label">{yearMode==='MONTH'?format(parseISO(`${period}-01`),'MMMM yyyy'):`${settings?.reportingYear==='FY'?'FY ':''}${period.split('-')[0]}${settings?.reportingYear==='FY'?`–${Number(period.split('-')[0])+1}`:''}`}</strong><button className="icon-btn" onClick={()=>setPeriod(yearMode==='MONTH'?addMonthsKey(period,1):String(Number(period.split('-')[0])+1))}><ChevronRight/></button><select value={group} onChange={e=>setGroup(e.target.value as typeof group)}><option value="CATEGORY">Group: Category</option><option value="SUBCATEGORY">Group: Subcategory</option><option value="ACCOUNT">Group: Account</option></select><select value={metric} onChange={e=>setMetric(e.target.value as typeof metric)}><option value="AMOUNT">Metric: Amount</option><option value="COUNT">Metric: Count</option><option value="PERCENT">Metric: Percent</option></select></section>
 {filterOpen&&<section className="panel compact-filter"><div className="panel-header"><div><h2>Filters</h2><p>Selected filters appear as removable pills.</p></div><button className="text-link" onClick={clear}>Clear all</button></div><div className="filter-controls"><label>Category<select value="" onChange={e=>{const id=e.target.value;if(id&&!categoryIds.includes(id))setCategoryIds([...categoryIds,id]);}}><option value="">Select category…</option>{roots.map(c=><option key={c.id} value={c.id} disabled={categoryIds.includes(c.id)}>{c.name}</option>)}</select></label><label>Subcategory<select value="" onChange={e=>{const id=e.target.value;if(id&&!subcategoryIds.includes(id))setSubcategoryIds([...subcategoryIds,id]);}}><option value="">Select subcategory…</option>{subs.map(c=><option key={c.id} value={c.id} disabled={selectedRootSet.has(c.parentId||'')}>{cats.find(p=>p.id===c.parentId)?.name} · {c.name}</option>)}</select></label><label>Account<select value="" onChange={e=>{const id=e.target.value;if(id&&!accountIds.includes(id))setAccountIds([...accountIds,id]);}}><option value="">Select account…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><div className="filter-chips">{categoryIds.map(id=><button key={id} onClick={()=>setCategoryIds(categoryIds.filter(x=>x!==id))}>{cats.find(c=>c.id===id)?.name} ×</button>)}{subcategoryIds.map(id=><button key={id} onClick={()=>setSubcategoryIds(subcategoryIds.filter(x=>x!==id))}>{cats.find(c=>c.id===id)?.name} ×</button>)}{accountIds.map(id=><button key={id} onClick={()=>setAccountIds(accountIds.filter(x=>x!==id))}>{accounts.find(a=>a.id===id)?.name} ×</button>)}</div></section>}
 <section className="metric-grid"><div className="metric-card"><span>Filtered spend</span><strong>{formatCurrency(total)}</strong><small>{rows.length} expenses</small></div><div className="metric-card"><span>Top group</span><strong>{grouped[0]?.name||'—'}</strong><small>{grouped[0]?formatCurrency(grouped[0].amount):'No data'}</small></div></section>
 <section className="report-grid"><div className="panel"><div className="panel-header"><div><h2>{group==='CATEGORY'?'Category':group==='SUBCATEGORY'?'Subcategory':'Account'} spend</h2><p>Tap a value to update the trend below.</p></div></div>{grouped.length?<><div className="chart-box"><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={grouped} dataKey="amount" nameKey="name" outerRadius="72%" label={({name,percent})=>`${name} ${Number(percent).toFixed(0)}%`} onClick={(_,i)=>setSelectedDrill(grouped[i]?.id||'')}>{grouped.map((g,i)=><Cell key={g.id} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={v=>[formatCurrency(Number(v)),'Spend']}/></PieChart></ResponsiveContainer></div><div className="stacked-list">{grouped.map(g=><button className={`stat-row clickable ${selectedDrill===g.id?'selected-row':''}`} key={g.id} onClick={()=>setSelectedDrill(g.id)}><span>{g.name} · {g.percent.toFixed(0)}%</span><strong>{formatCurrency(g.amount)}</strong></button>)}</div></>:<div className="empty-state" style={{margin:18}}><h3>No data</h3><p>Adjust the report filters.</p></div>}</div>
 <div className="panel"><div className="panel-header"><div><h2>Trend {selectedDrill?'· '+(cats.find(c=>c.id===selectedDrill)?.name||selectedDrill):''}</h2><p>Line chart; yearly view accumulates each month.</p></div><LineIcon size={18}/></div><div className="chart-box"><ResponsiveContainer width="100%" height={320}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" stroke="#252a32"/><XAxis dataKey="label" stroke="#78808e"/><YAxis stroke="#78808e"/><Tooltip formatter={(v)=>[metric==='COUNT'?v:formatCurrency(Number(v)),metric==='COUNT'?'Transactions':'Spend']}/><Line type="monotone" dataKey={metric==='COUNT'?'count':'amount'} stroke="#7c8cff" strokeWidth={3} dot={{r:3}}/></LineChart></ResponsiveContainer></div></div></section>
 {saved.length>0&&<section className="panel"><div className="panel-header"><div><h2>Saved reports</h2><p>Reusable reporting combinations.</p></div></div><div className="stacked-list">{saved.map((r,i)=><div className="stat-row" key={`${r.name}-${i}`}><button className="clickable" onClick={()=>{setCategoryIds(r.categoryIds);setSubcategoryIds(r.subcategoryIds);setAccountIds(r.accountIds);setMetric(r.metric as typeof metric);setGroup(r.group as typeof group);}}><strong>{r.name}</strong></button><button className="icon-btn small danger-icon" onClick={()=>{const next=saved.filter((_,x)=>x!==i);setSaved(next);localStorage.setItem('expense-saved-reports',JSON.stringify(next));}}><Trash2 size={13}/></button></div>)}</div></section>}
 </div>;
}
