import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../db/database';
export const useTransactions=()=>useLiveQuery(()=>db.transactions.filter(t=>!t.deletedAt).toArray(),[],[]);
export const useAccounts=()=>useLiveQuery(()=>db.accounts.filter(a=>a.active).toArray(),[],[]);
export const useCategories=()=>useLiveQuery(()=>db.categories.filter(c=>c.active).sortBy('sortOrder'),[],[]);
export const useReviewQueue=()=>useLiveQuery(()=>db.reviewQueue.where('status').equals('PENDING').toArray(),[],[]);
export const useRecurringRules=()=>useLiveQuery(()=>db.recurringRules.toArray(),[],[]);
export const useBudgets=()=>useLiveQuery(()=>db.budgets.toArray(),[],[]);
export const useInvestments=()=>useLiveQuery(()=>db.investments.orderBy('date').reverse().toArray(),[],[]);
export const useInterestAccounts=()=>useLiveQuery(()=>db.interestAccounts.filter(x=>x.active).toArray(),[],[]);
export const useProjectedIncome=()=>useLiveQuery(()=>db.projectedIncomeEvents.toArray(),[],[]);
export const useSavedReports=()=>useLiveQuery(()=>db.savedReports.orderBy('updatedAt').reverse().toArray(),[],[]);
export const useSettings=()=>useLiveQuery(()=>db.settings.get('app'),[]);
