import { useMemo } from 'react';
import { AlertCircle, ChevronRight } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useAccounts, useBudgets, useCategories, useReviewQueue, useSettings, useTransactions, useRecurringRules } from '../hooks/useDb';
import { formatCurrency } from '../utils/format';
import TransactionList from '../components/TransactionList';
import { Pie, PieChart, ResponsiveContainer, Cell, Tooltip } from 'recharts';
const COLORS=['#5f72ff','#4fd39a','#f2bd5c','#e37b7b','#72c9ef','#bb8be8'];
export default function Home(){
 const navigate=useNavigate(), tx=useTransactions()??[],accounts=useAccounts()??[],categories=useCategories()??[],review=useReviewQueue()??[],budgets=useBudgets()??[],rules=useRecurringRules()??[],settings=useSettings();
 const now=new Date(); const monthTx=useMemo(()=>tx.filter(t=>{const d=new Date(t.transactionDateTime);return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth();}),[tx]);
 const spent=monthTx.filter(t=>t.type==='EXPENSE').reduce((s,t)=>s+t.amount,0), income=monthTx.filter(t=>t.type==='INCOME').reduce((s,t)=>s+t.amount,0);
 const overallBudget=budgets.find(b=>!b.categoryId&&b.period==='MONTHLY'); const budget=overallBudget?.amount??0; const remaining=Math.max(0,budget-spent); const used=budget?Math.min(100,(spent/budget)*100):0;
 const estimated=useMemo(()=>settings?.showEstimatedDues===false?0:rules.filter(r=>r.active&&r.type==='EXPENSE').reduce((s,r)=>{const d=new Date(r.nextDueDate);return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()?s+r.amount:s;},0),[rules,settings?.showEstimatedDues]);
 const catData=useMemo(()=>{const m=new Map<string,number>();monthTx.filter(t=>t.type==='EXPENSE').forEach(t=>m.set(t.categoryId||'uncategorized',(m.get(t.categoryId||'uncategorized')||0)+t.amount));return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,7).map(([id,amount])=>({id,name:categories.find(c=>c.id===id)?.name||'Uncategorized',amount}));},[monthTx,categories]);
 const recent=tx.slice().sort((a,b)=>+new Date(b.transactionDateTime)-+new Date(a.transactionDateTime)).slice(0,8);
 return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Current month</span><h1>{now.toLocaleDateString('en-IN',{month:'long',year:'numeric'})}</h1><p className="muted">Record first. Understand your money at a glance.</p></div></section>
 {review.length>0&&<Link to="/review" className="review-alert"><AlertCircle size={18}/><div><strong>{review.length} transaction{review.length===1?'':'s'} need review</strong><span>Confirm them before they enter your reports.</span></div><ChevronRight size={17}/></Link>}
 <section className="panel budget-hero"><div className="panel-header"><div><h2>Budget</h2><p>{budget?`${formatCurrency(remaining)} remaining to spend`:'Set an overall monthly budget to enable this view.'}</p></div><Link to="/budgets" className="text-link">Manage</Link></div><div className="budget-big-row"><strong>{budget?formatCurrency(spent):'—'}</strong><span>{budget?`of ${formatCurrency(budget)}`:'No budget set'}</span></div>{budget&&<><div className="progress-track large"><span style={{width:`${used}%`}}/></div><div className="budget-labels"><span>{formatCurrency(budget - spent - estimated)} net remaining this month</span><span>{Math.round((spent/budget)*100)}% used</span></div></>}</section>
 {settings?.showEstimatedDues!==false&&<section className="panel dues-panel"><div className="panel-header"><div><h2>Estimated dues</h2><p>Upcoming recurring payments this month</p></div><Link to="/recurring" className="text-link">Manage</Link></div><div className="budget-big-row"><strong className="warning-text">{formatCurrency(estimated)}</strong><span>future expenses</span></div><div className="progress-track large warning"><span style={{width:`${Math.min(100,budget?estimated/budget*100:0)}%`}}/></div></section>}
 <section className="panel"><div className="panel-header"><div><h2>Spend by category</h2><p>Tap a category to open its report.</p></div><Link to="/stats" className="text-link">Stats</Link></div>{catData.length?<><div className="chart-box"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={catData} dataKey="amount" nameKey="name" innerRadius="48%" outerRadius="76%">{catData.map((x,i)=><Cell key={x.id} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip formatter={v=>formatCurrency(Number(v))}/></PieChart></ResponsiveContainer></div><div className="stacked-list">{catData.map((x,i)=><button key={x.id} className="stat-row clickable" onClick={()=>navigate(`/stats?category=${x.id}`)}><span><i className="legend-dot" style={{background:COLORS[i%COLORS.length]}}/>{x.name}</span><strong>{formatCurrency(x.amount)}</strong></button>)}</div></>:<div className="empty-state"><h3>No expenses this month</h3><p>Use the + button to record your first transaction.</p></div>}</section>
 <section className="panel"><div className="panel-header"><div><h2>Recent transactions</h2><p>Latest confirmed activity</p></div><Link to="/transactions" className="text-link">View all</Link></div><TransactionList transactions={recent} accounts={accounts} categories={categories} onSelect={t=>navigate(`/transactions/${t.id}`)}/></section>
 </div>;
}
