import { useMemo, useState } from 'react';
import { Calculator, Pencil, Plus, Trash2 } from 'lucide-react';
import { useAccounts, useInterestAccounts, useProjectedIncome } from '../hooks/useDb';
import { db } from '../db/database';
import { calculateFdInterest, ensureProjectedInterest } from '../services/interestService';
import { newId } from '../utils/id';
import { formatCurrency } from '../utils/format';
import type { Compounding, InterestAccount, InterestAccountType } from '../types/models';
import { queueEntitySync } from '../services/syncService';
export default function InterestReturns(){
 const accounts=useAccounts()??[],items=useInterestAccounts()??[],events=useProjectedIncome()??[];const [principal,setPrincipal]=useState('100000'),[rate,setRate]=useState('7.1'),[months,setMonths]=useState('12'),[calc,setCalc]=useState<number|null>(null);const [open,setOpen]=useState(false),[editing,setEditing]=useState<InterestAccount|null>(null);const [name,setName]=useState(''),[type,setType]=useState<InterestAccountType>('FIXED_DEPOSIT'),[amount,setAmount]=useState(''),[iRate,setIRate]=useState('7.1'),[opening,setOpening]=useState(new Date().toISOString().slice(0,10)),[maturity,setMaturity]=useState(''),[compounding,setCompounding]=useState<Compounding>('QUARTERLY'),[linkedAccount,setLinkedAccount]=useState(''),[auto,setAuto]=useState(true);
 const projected=useMemo(()=>items.reduce((s,a)=>s+calculateFdInterest(a.principal,a.interestRate,a.maturityMonths||12,a.compounding),0),[items]);const expected=events.filter(e=>e.status==='PROJECTED').reduce((s,e)=>s+e.amount,0);
 const save=async()=>{if(!name.trim()||!Number(amount))return;const now=new Date().toISOString();const obj:InterestAccount={id:editing?.id||newId('interest'),name:name.trim(),type,principal:Number(amount),recurringAmount:type==='RECURRING_DEPOSIT'?Number(amount):undefined,interestRate:Number(iRate),compounding,openingDate:new Date(`${opening}T12:00:00`).toISOString(),maturityDate:maturity?new Date(`${maturity}T12:00:00`).toISOString():undefined,maturityMonths:maturity?undefined:Number(monthsFromDates(opening,maturity)),payoutFrequency:'MATURITY',accountId:linkedAccount||undefined,active:true,autoRecordInterest:auto,createdAt:editing?.createdAt||now,updatedAt:now};await db.interestAccounts.put(obj);await ensureProjectedInterest(obj);await queueEntitySync('INTEREST_ACCOUNT',obj.id,editing?'UPDATE':'CREATE',obj);setOpen(false);};
 const edit=(a:InterestAccount)=>{setEditing(a);setName(a.name);setType(a.type);setAmount(String(a.principal));setIRate(String(a.interestRate));setOpening(a.openingDate.slice(0,10));setMaturity(a.maturityDate?.slice(0,10)||'');setCompounding(a.compounding);setLinkedAccount(a.accountId||'');setAuto(a.autoRecordInterest);setOpen(true);};
 return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Tax planning</span><h1>Interest & Returns</h1><p className="muted">Project FD, RD and savings interest for advance-tax and ITR planning. Projections are estimates.</p></div></section>
 <section className="panel"><div className="panel-header"><div><h2>Interest calculator</h2><p>Quick estimate without saving an account.</p></div><Calculator size={18}/></div><div className="form-grid settings-grid-like"><label>Principal<input inputMode="decimal" value={principal} onChange={e=>setPrincipal(e.target.value)}/></label><label>Annual rate %<input inputMode="decimal" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Months<input inputMode="numeric" value={months} onChange={e=>setMonths(e.target.value)}/></label><label>Compounding<select value={compounding} onChange={e=>setCompounding(e.target.value as Compounding)}><option value="SIMPLE">Simple</option><option value="MONTHLY">Monthly</option><option value="QUARTERLY">Quarterly</option><option value="HALF_YEARLY">Half-yearly</option><option value="YEARLY">Yearly</option></select></label></div><button className="primary-btn" onClick={()=>setCalc(calculateFdInterest(Number(principal),Number(rate),Number(months),compounding))}>Calculate</button>{calc!==null&&<div className="calculation-result"><span>Estimated interest</span><strong>{formatCurrency(calc)}</strong><small>Maturity value: {formatCurrency(Number(principal)+calc)}</small></div>}</section>
 <section className="metric-grid"><div className="metric-card"><span>Projected interest</span><strong>{formatCurrency(projected)}</strong><small>Across saved deposits</small></div><div className="metric-card"><span>Upcoming interest</span><strong>{formatCurrency(expected)}</strong><small>Future income events</small></div></section>
 <section className="panel"><div className="panel-header"><div><h2>Interest-bearing deposits</h2><p>Keep actual accounts separate from projected income.</p></div><button className="primary-btn" onClick={()=>{setEditing(null);setName('');setType('FIXED_DEPOSIT');setAmount('');setMaturity('');setOpen(true)}}><Plus size={15}/> Add deposit</button></div>{items.length===0?<div className="empty-state"><h3>No deposits added</h3><p>Add your FDs, RDs and savings accounts for projection.</p></div>:<div className="transaction-list">{items.map(a=><div className="transaction-row" key={a.id}><div className="transaction-main"><strong>{a.name}</strong><span>{a.type.replace('_',' ')} · {a.interestRate}% · opened {new Date(a.openingDate).toLocaleDateString('en-IN')}</span></div><div className="transaction-meta"><strong className="positive">{formatCurrency(calculateFdInterest(a.principal,a.interestRate,a.maturityMonths||12,a.compounding))}</strong><button className="icon-btn small" onClick={()=>edit(a)}><Pencil size={13}/></button><button className="icon-btn small danger-icon" onClick={async()=>{await db.interestAccounts.update(a.id,{active:false,updatedAt:new Date().toISOString()});await queueEntitySync('INTEREST_ACCOUNT',a.id,'DELETE',{id:a.id});}}><Trash2 size={13}/></button></div></div>)}</div>}</section>
 {open&&<div className="modal-backdrop"><div className="modal"><div className="panel-header"><div><h2>{editing?'Edit deposit':'Add interest account'}</h2><p>Use your bank's actual compounding convention for the best estimate.</p></div><button className="icon-btn" onClick={()=>setOpen(false)}>×</button></div><div className="form-grid"><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="HDFC FD"/></label><label>Type<select value={type} onChange={e=>setType(e.target.value as InterestAccountType)}><option value="FIXED_DEPOSIT">Fixed Deposit</option><option value="RECURRING_DEPOSIT">Recurring Deposit</option><option value="SAVINGS_ACCOUNT">Savings Account</option></select></label><label>{type==='RECURRING_DEPOSIT'?'Monthly deposit':'Principal'}<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Interest %<input inputMode="decimal" value={iRate} onChange={e=>setIRate(e.target.value)}/></label><label>Opening date<input type="date" value={opening} onChange={e=>setOpening(e.target.value)}/></label><label>Maturity date<input type="date" value={maturity} onChange={e=>setMaturity(e.target.value)}/></label><label>Compounding<select value={compounding} onChange={e=>setCompounding(e.target.value as Compounding)}><option value="SIMPLE">Simple</option><option value="MONTHLY">Monthly</option><option value="QUARTERLY">Quarterly</option><option value="HALF_YEARLY">Half-yearly</option><option value="YEARLY">Yearly</option></select></label><label>Linked account<select value={linkedAccount} onChange={e=>setLinkedAccount(e.target.value)}><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><label className="checkbox-row"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Project future interest and automatically record it as Interest income when due</label><button className="primary-btn record-btn" onClick={()=>void save()}>{editing?'Update deposit':'Save deposit'}</button></div></div>}
 </div>;
}
function monthsFromDates(a:string,b:string){const x=new Date(a),y=new Date(b);return Math.max(1,(y.getFullYear()-x.getFullYear())*12+y.getMonth()-x.getMonth());}
