import { useMemo, useState } from 'react';
import { LineChart as LineIcon, Plus, Trash2 } from 'lucide-react';
import { useAccounts, useCategories, useInvestments, useTransactions } from '../hooks/useDb';
import { db } from '../db/database';
import { newId } from '../utils/id';
import { formatCurrency } from '../utils/format';
import { queueEntitySync } from '../services/syncService';
import { createTransaction, deleteTransaction } from '../services/transactionService';
export default function Investments(){
 const entries=useInvestments()??[],accounts=useAccounts()??[],categories=useCategories()??[],tx=useTransactions()??[];const [name,setName]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[notes,setNotes]=useState(''),[assetType,setAssetType]=useState<'STOCK'|'MUTUAL_FUND'|'SIP'|'FIXED_DEPOSIT'|'GOLD'|'RETIREMENT_PF'|'OTHER'>('MUTUAL_FUND'),[accountId,setAccountId]=useState('');
 const total=entries.filter(e=>e.type==='CONTRIBUTION').reduce((s,e)=>s+e.amount,0),thisYear=entries.filter(e=>new Date(e.date).getFullYear()===new Date().getFullYear()&&e.type==='CONTRIBUTION').reduce((s,e)=>s+e.amount,0),thisMonth=entries.filter(e=>{const d=new Date(e.date);const n=new Date();return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()&&e.type==='CONTRIBUTION';}).reduce((s,e)=>s+e.amount,0);
 async function add(){const value=Number(amount);if(!name.trim()||!value||!accountId)return;const now=new Date().toISOString();const inv={id:newId('inv'),date:new Date(`${date}T12:00:00`).toISOString(),name:name.trim(),assetType,type:'CONTRIBUTION' as const,amount:value,accountId,notes:notes.trim()||undefined,createdAt:now,updatedAt:now,syncStatus:'PENDING' as const};const root=categories.find(c=>c.name==='Investments'&&!c.parentId);const sub=categories.find(c=>c.parentId===root?.id&&c.name===assetLabel(assetType));const t=await createTransaction({type:'INVESTMENT',amount:value,transactionDateTime:inv.date,accountId,categoryId:root?.id,subcategoryId:sub?.id,merchant:name,notes,source:'MANUAL',sourceId:`investment:${inv.id}`});await db.investments.put({...inv,transactionId:t.id});await queueEntitySync('INVESTMENT',inv.id,'CREATE',{...inv,transactionId:t.id});setName('');setAmount('');setNotes('');}
 return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Wealth</span><h1>Investments</h1><p className="muted">Investment activity also appears in the main transaction ledger.</p></div></section><section className="metric-grid"><div className="metric-card"><span>This month</span><strong>{formatCurrency(thisMonth)}</strong></div><div className="metric-card"><span>This year</span><strong>{formatCurrency(thisYear)}</strong></div><div className="metric-card"><span>All time</span><strong>{formatCurrency(total)}</strong></div></section>
 <section className="panel"><div className="panel-header"><div><h2>Record investment</h2><p>Purchase date and notes are stored with the investment.</p></div><LineIcon size={18}/></div><div className="form-grid settings-grid-like"><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="SBI Bluechip"/></label><label>Amount<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Purchase date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Asset type<select value={assetType} onChange={e=>setAssetType(e.target.value as typeof assetType)}><option value="STOCK">Stocks</option><option value="MUTUAL_FUND">Mutual Fund</option><option value="SIP">SIP</option><option value="FIXED_DEPOSIT">Fixed Deposit</option><option value="GOLD">Gold</option><option value="RETIREMENT_PF">Retirement/PF</option><option value="OTHER">Other</option></select></label><label>Account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="wide">Notes<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional"/></label></div><button className="primary-btn" onClick={()=>void add()}><Plus size={16}/> Add investment</button></section>
 <section className="panel"><div className="panel-header"><div><h2>Investment activity</h2></div></div>{entries.length===0?<div className="empty-state"><h3>No investment records</h3></div>:<div className="transaction-list">{entries.map(e=><div className="transaction-row" key={e.id}><div className="transaction-main"><strong>{e.name}</strong><span>{assetLabel(e.assetType)} · {new Date(e.date).toLocaleDateString('en-IN')}{e.notes?` · ${e.notes}`:''}</span></div><div className="transaction-meta"><strong className="investment-text">{formatCurrency(e.amount)}</strong><button className="icon-btn small danger-icon" onClick={async()=>{if(e.transactionId)await deleteTransaction(e.transactionId);await db.investments.delete(e.id);await queueEntitySync('INVESTMENT',e.id,'DELETE',{id:e.id});}}><Trash2 size={13}/></button></div></div>)}</div>}</section></div>;
}
function assetLabel(v:string){return v==='MUTUAL_FUND'?'Mutual Fund':v==='FIXED_DEPOSIT'?'Fixed Deposit':v==='RETIREMENT_PF'?'Retirement/PF':v==='STOCK'?'Stocks':v==='SIP'?'SIP':v==='GOLD'?'Gold':'Other';}
