import { useEffect, useMemo, useState } from 'react';
import { Pause, Play, Plus, RefreshCcw, Trash2 } from 'lucide-react';
import { useAccounts, useCategories, useRecurringRules } from '../hooks/useDb';
import { db } from '../db/database';
import type { Frequency } from '../types/models';
import { newId } from '../utils/id';
import { queueEntitySync } from '../services/syncService';

export default function Recurring(){
  const rules=useRecurringRules();const accounts=useAccounts();const categories=useCategories();const [open,setOpen]=useState(false);const [name,setName]=useState('');const [amount,setAmount]=useState('');const [frequency,setFrequency]=useState<Frequency>('MONTHLY');const [day,setDay]=useState('1');const [accountId,setAccountId]=useState('');const [categoryId,setCategoryId]=useState('');const [subcategoryId,setSubcategoryId]=useState('');
  useEffect(()=>{if(!accountId)setAccountId(accounts.find(a=>a.isDefault)?.id||accounts[0]?.id||'');},[accounts,accountId]);
  const subs=useMemo(()=>categories.filter(c=>c.parentId===categoryId),[categories,categoryId]);
  async function createRule(){if(!name.trim()||!amount||!accountId)return;const now=new Date();const requested=Math.min(Math.max(Number(day),1),31);const lastDay=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();let next=new Date(now.getFullYear(),now.getMonth(),Math.min(requested,lastDay),12,0,0);if(next<now)next=new Date(now.getFullYear(),now.getMonth()+1,Math.min(requested,new Date(now.getFullYear(),now.getMonth()+2,0).getDate()),12,0,0);const rule={id:newId('rule'),name:name.trim(),amount:Number(amount),type:'EXPENSE' as const,accountId,categoryId:categoryId||undefined,subcategoryId:subcategoryId||undefined,frequency,dayOfMonth:requested,startDate:now.toISOString(),nextDueDate:next.toISOString(),active:true,createdAt:now.toISOString(),updatedAt:now.toISOString()}; await db.recurringRules.put(rule); await queueEntitySync('RECURRING_RULE', rule.id, 'CREATE', rule);setName('');setAmount('');setOpen(false);}
  return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Automation</span><h1>Recurring Payments</h1><p className="muted">Scheduled rules generate normal transactions when the app is opened/resumed.</p></div><button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={17}/> Add recurring</button></section>
  <div className="recurring-grid">{rules.length===0?<div className="empty-state"><div className="empty-icon">↻</div><h3>No recurring rules</h3><p>Add subscriptions, EMI, RD, rent or other automatic payments.</p></div>:rules.map(r=><article key={r.id} className="recurring-card"><div className="recurring-icon"><RefreshCcw size={17}/></div><div className="recurring-info"><strong>{r.name}</strong><span>₹{r.amount.toLocaleString('en-IN')} · {r.frequency.toLowerCase()} · day {r.dayOfMonth??'—'}</span><small>{r.active?'Next':'Paused'}: {new Date(r.nextDueDate).toLocaleDateString('en-IN')}</small></div><button className="icon-btn" onClick={async()=>{const updated={...r,active:!r.active,updatedAt:new Date().toISOString()};await db.recurringRules.put(updated);await queueEntitySync('RECURRING_RULE',r.id,'UPDATE',updated);}}>{r.active?<Pause size={16}/>:<Play size={16}/>}</button><button className="icon-btn danger-icon" onClick={async()=>{const updated={...r,active:false,updatedAt:new Date().toISOString()};await db.recurringRules.put(updated);await queueEntitySync('RECURRING_RULE',r.id,'UPDATE',updated);}}><Trash2 size={15}/></button></article>)}</div>
  {open&&<div className="modal-backdrop"><div className="modal"><div className="panel-header"><div><h2>New recurring payment</h2><p>Subscription, EMI, RD, rent, insurance, SIP, etc.</p></div><button className="icon-btn" onClick={()=>setOpen(false)}>×</button></div><div className="form-grid"><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Netflix"/></label><label>Amount<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="649"/></label><label>Frequency<select value={frequency} onChange={e=>setFrequency(e.target.value as Frequency)}><option value="MONTHLY">Monthly</option><option value="WEEKLY">Weekly</option><option value="YEARLY">Yearly</option></select></label><label>Day<input type="number" min="1" max="31" value={day} onChange={e=>setDay(e.target.value)}/></label><label>Account<select value={accountId} onChange={e=>setAccountId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Category<select value={categoryId} onChange={e=>{setCategoryId(e.target.value);setSubcategoryId('')}}><option value="">Optional</option>{categories.filter(c=>!c.parentId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{categoryId&&<label>Subcategory<select value={subcategoryId} onChange={e=>setSubcategoryId(e.target.value)}><option value="">Optional</option>{subs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}</div><button className="primary-btn record-btn" onClick={createRule}>Save recurring rule</button></div></div>}
  </div>;
}
