import { useEffect, useMemo, useState } from 'react';
import { Pause, Play, Plus, RefreshCcw, Pencil, Trash2 } from 'lucide-react';
import { useAccounts, useCategories, useRecurringRules } from '../hooks/useDb';
import { db } from '../db/database';
import type { Frequency, RecurringRule } from '../types/models';
import { newId } from '../utils/id';
import { queueEntitySync } from '../services/syncService';
import { frequencyLabel } from '../services/recurringService';
import { addMonths, addWeeks, addYears, setDate } from 'date-fns';
const nextFrom=(frequency:Frequency,date:Date,day:number)=>{switch(frequency){case'DAILY':return new Date(date.getTime()+86400000);case'WEEKLY':return addWeeks(date,1);case'BIWEEKLY':return addWeeks(date,2);case'MONTHLY':return setDate(addMonths(date,1),Math.min(day,new Date(date.getFullYear(),date.getMonth()+2,0).getDate()));case'BIMONTHLY':return setDate(addMonths(date,2),Math.min(day,new Date(date.getFullYear(),date.getMonth()+3,0).getDate()));case'QUARTERLY':return setDate(addMonths(date,3),Math.min(day,new Date(date.getFullYear(),date.getMonth()+4,0).getDate()));case'HALF_YEARLY':return setDate(addMonths(date,6),Math.min(day,new Date(date.getFullYear(),date.getMonth()+7,0).getDate()));case'YEARLY':return addYears(date,1);}};
export default function Recurring(){
 const rules=useRecurringRules()??[],accounts=useAccounts()??[],categories=useCategories()??[];const [editing,setEditing]=useState<RecurringRule|null>(null),[open,setOpen]=useState(false);const [name,setName]=useState(''),[amount,setAmount]=useState(''),[frequency,setFrequency]=useState<Frequency>('MONTHLY'),[day,setDay]=useState('1'),[startDate,setStartDate]=useState(new Date().toISOString().slice(0,10)),[accountId,setAccountId]=useState(''),[categoryId,setCategoryId]=useState(''),[subcategoryId,setSubcategoryId]=useState('');
 useEffect(()=>{if(!accountId)setAccountId(accounts.find(a=>a.isDefault)?.id||accounts[0]?.id||'');},[accounts,accountId]);const subs=useMemo(()=>categories.filter(c=>c.parentId===categoryId),[categories]);
 const openNew=()=>{setEditing(null);setName('');setAmount('');setFrequency('MONTHLY');setDay('1');setStartDate(new Date().toISOString().slice(0,10));setCategoryId('');setSubcategoryId('');setOpen(true);};
 const openEdit=(r:RecurringRule)=>{setEditing(r);setName(r.name);setAmount(String(r.amount));setFrequency(r.frequency);setDay(String(r.dayOfMonth||1));setStartDate(r.startDate.slice(0,10));setAccountId(r.accountId);setCategoryId(r.categoryId||'');setSubcategoryId(r.subcategoryId||'');setOpen(true);};
 const save=async()=>{if(!name.trim()||!Number(amount)||!accountId)return;const now=new Date();const start=new Date(`${startDate}T12:00:00`);const requested=Math.min(Math.max(Number(day),1),31);let due=new Date(start);due.setHours(12,0,0,0);if(due.getFullYear()===now.getFullYear()&&due.getMonth()===now.getMonth()&&due<now){} else if(due<now){due=new Date(now.getFullYear(),now.getMonth(),Math.min(requested,new Date(now.getFullYear(),now.getMonth()+1,0).getDate()),12);}const root=categories.find(c=>c.id===categoryId);const rule:RecurringRule={id:editing?.id||newId('rule'),name:name.trim(),amount:Number(amount),type:'EXPENSE',accountId,categoryId:root?.parentId||root?.id||undefined,subcategoryId:subcategoryId||undefined,frequency,dayOfMonth:requested,startDate:start.toISOString(),nextDueDate:due.toISOString(),active:editing?.active??true,createdAt:editing?.createdAt||now.toISOString(),updatedAt:now.toISOString()};await db.recurringRules.put(rule);await queueEntitySync('RECURRING_RULE',rule.id,editing?'UPDATE':'CREATE',rule);setOpen(false);};
 const remove=async(r:RecurringRule)=>{if(!confirm(`Delete recurring payment "${r.name}"?`))return;await db.recurringRules.update(r.id,{active:false,updatedAt:new Date().toISOString()});await queueEntitySync('RECURRING_RULE',r.id,'DELETE',{id:r.id});};
 return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Automation</span><h1>Recurring Payments</h1><p className="muted">Subscriptions, EMI, RD, rent, insurance and other scheduled entries.</p></div><button className="primary-btn" onClick={openNew}><Plus size={17}/> Add recurring</button></section><div className="recurring-grid">{rules.length===0?<div className="empty-state"><h3>No recurring rules</h3><p>Add a scheduled payment.</p></div>:rules.map(r=><article key={r.id} className={`recurring-card ${r.active?'':'paused'}`}><div className="recurring-icon"><RefreshCcw size={17}/></div><div className="recurring-info"><strong>{r.name}</strong><span>{formatCurrency(r.amount)} · {frequencyLabel(r.frequency)} · day {r.dayOfMonth??'—'}</span><small>{r.active?'Next':'Paused'}: {new Date(r.nextDueDate).toLocaleDateString('en-IN')}</small></div><button className="icon-btn" onClick={async()=>{const u={...r,active:!r.active,updatedAt:new Date().toISOString()};await db.recurringRules.put(u);await queueEntitySync('RECURRING_RULE',r.id,'UPDATE',u);}}>{r.active?<Pause size={16}/>:<Play size={16}/>}</button><button className="icon-btn" onClick={()=>openEdit(r)}><Pencil size={15}/></button><button className="icon-btn danger-icon" onClick={()=>void remove(r)}><Trash2 size={15}/></button></article>)}</div>
 {open&&<div className="modal-backdrop"><div className="modal"><div className="panel-header"><div><h2>{editing?'Edit recurring payment':'New recurring payment'}</h2><p>Past start dates generate only the current month's entry, not historical duplicates.</p></div><button className="icon-btn" onClick={()=>setOpen(false)}>×</button></div><div className="form-grid"><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Insurance"/></label><label>Amount<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Frequency<select value={frequency} onChange={e=>setFrequency(e.target.value as Frequency)}>{(['DAILY','WEEKLY','BIWEEKLY','MONTHLY','BIMONTHLY','QUARTERLY','HALF_YEARLY','YEARLY'] as Frequency[]).map(f=><option key={f} value={f}>{frequencyLabel(f)}</option>)}</select></label><label>Day<input type="number" min="1" max="31" value={day} onChange={e=>setDay(e.target.value)}/></label><label>Start date<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>Account<select value={accountId} onChange={e=>setAccountId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Category<select value={categoryId} onChange={e=>{setCategoryId(e.target.value);setSubcategoryId('')}}><option value="">Optional</option>{categories.filter(c=>!c.parentId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{categoryId&&<label>Subcategory<select value={subcategoryId} onChange={e=>setSubcategoryId(e.target.value)}><option value="">Optional</option>{subs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}</div><button className="primary-btn record-btn" onClick={()=>void save()}>{editing?'Update rule':'Save recurring rule'}</button></div></div>}
 </div>;
}
function formatCurrency(v:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v)}
