import { useEffect, useRef, useState } from 'react';
import { DatabaseBackup, Download, FileUp, RefreshCcw, ShieldCheck, Smartphone, Unlock, Plus, Trash2, Pencil } from 'lucide-react';
import { db } from '../db/database';
import { restoreFromGoogleSheets, syncWithGoogleSheets } from '../services/googleSheetsService';
import { useAccounts, useSettings } from '../hooks/useDb';
import { disableLock, enablePasskey, setLocalPin, webAuthnAvailable } from '../services/authService';
import { exportCsv, exportExcel, exportJson, clearLocalData } from '../services/exportService';
import { newId } from '../utils/id';
export default function Settings(){
 const settings=useSettings();const accounts=useAccounts()??[];const fileRef=useRef<HTMLInputElement>(null);const [message,setMessage]=useState('');const [pin,setPin]=useState('');const [sheetUrl,setSheetUrl]=useState('');const [sheetToken,setSheetToken]=useState('');const [name,setName]=useState('');const [accountType,setAccountType]=useState('BANK_ACCOUNT');const [editingAccount,setEditingAccount]=useState<string|null>(null);
 useEffect(()=>{if(settings)document.documentElement.dataset.theme=settings.theme||'dark';},[settings?.theme]);
 const update=async(p:Partial<NonNullable<typeof settings>>)=>{const s=await db.settings.get('app');if(s)await db.settings.put({...s,...p});};
 const saveDefaults=async()=>{await update({defaultNeedWant:undefined,defaultEssentialDiscretionary:undefined,defaultFixedVariable:undefined});setMessage('Defaults saved.');};
 const saveSheets=async()=>{await update({googleSheetsEndpoint:sheetUrl||settings?.googleSheetsEndpoint,googleSheetsToken:sheetToken||settings?.googleSheetsToken,googleSheetsEnabled:Boolean(sheetUrl||settings?.googleSheetsEndpoint)});setMessage('Google Sheets connection saved.');};
 const sync=async()=>{const r=await syncWithGoogleSheets();setMessage(r.success?`Synced ${r.processed||0} changes.`:(r.message||'Sync failed.'));};
 const restore=async()=>{try{const r=await restoreFromGoogleSheets();setMessage(r.message);}catch(e){setMessage(e instanceof Error?e.message:'Restore failed.');}};
 const addAccount=async()=>{if(!name.trim())return;const now=new Date().toISOString();if(editingAccount){const old=await db.accounts.get(editingAccount);if(old){const a={...old,name:name.trim(),type:accountType as any,updatedAt:now};await db.accounts.put(a);}setEditingAccount(null);setName('');setMessage('Account updated.');return;}const existing=await db.accounts.toArray();const a={id:newId('account'),name:name.trim(),type:accountType as any,isDefault:existing.length===0,active:true,createdAt:now,updatedAt:now};if(a.isDefault)await db.accounts.toArray().then(xs=>Promise.all(xs.map(x=>db.accounts.update(x.id,{isDefault:false}))));await db.accounts.put(a);setName('');setMessage('Account added.');};
 const setDefault=async(id:string)=>{await db.transaction('rw',db.accounts,async()=>{await db.accounts.toCollection().modify({isDefault:false});await db.accounts.update(id,{isDefault:true});});await update({defaultAccountId:id});};
 const removeAccount=async(id:string)=>{if(accounts.length<=1){setMessage('Keep at least one account.');return;}if(!confirm('Archive this account? Existing transactions remain unchanged.'))return;await db.accounts.update(id,{active:false,updatedAt:new Date().toISOString()});if(settings?.defaultAccountId===id)await update({defaultAccountId:accounts.find(a=>a.id!==id)?.id});};
 const importBackup=async(file?:File)=>{if(!file)return;try{const data=JSON.parse(await file.text()) as any;await db.transaction('rw',[db.transactions,db.accounts,db.categories,db.recurringRules,db.reviewQueue,db.budgets,db.investments,db.interestAccounts,db.projectedIncomeEvents,db.savedReports,db.settings],async()=>{for(const k of ['transactions','accounts','categories','recurringRules','reviewQueue','budgets','investments','interestAccounts','projectedIncomeEvents','savedReports','settings'])if(Array.isArray(data[k]))await (db as any)[k].bulkPut(data[k]);});setMessage('Backup restored.');}catch(e){setMessage(e instanceof Error?e.message:'Import failed.');}};
 const lockPasskey=async()=>{try{await enablePasskey();setMessage('Face ID / passkey lock enabled.');}catch(e){setMessage(e instanceof Error?e.message:'Could not enable passkey lock.');}};const lockPin=async()=>{try{await setLocalPin(pin);setMessage('PIN lock enabled.');setPin('');}catch(e){setMessage(e instanceof Error?e.message:'Could not enable PIN lock.');}};
 return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Configuration</span><h1>Settings</h1><p className="muted">Local data, defaults, accounts, backup and device protection.</p></div></section>{message&&<div className="success-banner">{message}</div>}
 <section className="panel"><div className="panel-header"><div><h2>Appearance</h2><p>Choose how the app looks on this device.</p></div></div><div className="segmented"><button className={settings?.theme==='dark'?'active':''} onClick={()=>void update({theme:'dark'})}>Dark</button><button className={settings?.theme==='light'?'active':''} onClick={()=>void update({theme:'light'})}>Light</button><button className={settings?.theme==='system'?'active':''} onClick={()=>void update({theme:'system'})}>System</button></div></section>
 <section className="panel"><div className="panel-header"><div><h2>Default recording</h2><p>These values prefill quick transactions; they remain optional.</p></div></div><div className="settings-grid"><label>Default account<select value={settings?.defaultAccountId||''} onChange={e=>void update({defaultAccountId:e.target.value||undefined})}><option value="">None</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Need / Want<select value={settings?.defaultNeedWant||''} onChange={e=>void update({defaultNeedWant:(e.target.value||undefined) as any})}><option value="">No default</option><option value="NEED">Need</option><option value="WANT">Want</option></select></label><label>Essential / Discretionary<select value={settings?.defaultEssentialDiscretionary||''} onChange={e=>void update({defaultEssentialDiscretionary:(e.target.value||undefined) as any})}><option value="">No default</option><option value="ESSENTIAL">Essential</option><option value="DISCRETIONARY">Discretionary</option></select></label><label>Fixed / Variable<select value={settings?.defaultFixedVariable||''} onChange={e=>void update({defaultFixedVariable:(e.target.value||undefined) as any})}><option value="">No default</option><option value="FIXED">Fixed</option><option value="VARIABLE">Variable</option></select></label></div></section>
 <section className="panel"><div className="panel-header"><div><h2>Accounts</h2><p>Create or modify accounts used by transactions.</p></div></div><div className="form-grid settings-grid-like"><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Savings Account"/></label><label>Type<select value={accountType} onChange={e=>setAccountType(e.target.value)}><option value="BANK_ACCOUNT">Bank account</option><option value="CREDIT_CARD">Credit card</option><option value="CASH">Cash</option><option value="WALLET">Wallet</option><option value="INVESTMENT">Investment</option><option value="OTHER">Other</option></select></label></div><button className="primary-btn" onClick={()=>void addAccount()}>{editingAccount?<Pencil size={15}/>:<Plus size={15}/>} {editingAccount?'Update account':'Add account'}</button><div className="account-list">{accounts.map(a=><div className="account-row" key={a.id}><div><strong>{a.name}</strong><span>{a.type.replace('_',' ')} {a.isDefault?'· Default':''}</span></div><div className="inline-actions compact"><button className="secondary-btn" onClick={()=>{setEditingAccount(a.id);setName(a.name);setAccountType(a.type)}}><Pencil size={13}/> Edit</button><button className="secondary-btn" onClick={()=>void setDefault(a.id)} disabled={a.isDefault}>Make default</button><button className="icon-btn danger-icon" onClick={()=>void removeAccount(a.id)}><Trash2 size={14}/></button></div></div>)}</div></section>
 <section className="panel"><div className="panel-header"><div><h2>Google Sheets</h2><p>Optional reporting/backup layer. IndexedDB remains the local source of truth.</p></div><DatabaseBackup size={18}/></div><div className="settings-grid"><label>Web app URL<input value={sheetUrl} onChange={e=>setSheetUrl(e.target.value)} placeholder={settings?.googleSheetsEndpoint||'https://script.google.com/macros/s/.../exec'}/></label><label>Token<input type="password" value={sheetToken} onChange={e=>setSheetToken(e.target.value)} placeholder="Stored only in IndexedDB"/></label></div><div className="inline-actions"><button className="secondary-btn" onClick={()=>void saveSheets()}>Save connection</button><button className="primary-btn" onClick={()=>void sync()} disabled={!settings?.googleSheetsEnabled}>Sync</button><button className="secondary-btn" onClick={()=>void restore()} disabled={!settings?.googleSheetsEnabled}>Fetch from Sheet</button></div></section>
 <section className="panel"><div className="panel-header"><div><h2>Backup & data</h2><p>JSON is the full restore format. CSV and Excel are reporting exports.</p></div><Download size={18}/></div><div className="inline-actions"><button className="secondary-btn" onClick={()=>void exportJson()}>Export JSON</button><button className="secondary-btn" onClick={()=>void exportCsv()}>Export CSV</button><button className="secondary-btn" onClick={()=>void exportExcel()}>Export Excel</button><label className="secondary-btn file-btn"><FileUp size={15}/> Import JSON<input ref={fileRef} type="file" accept="application/json,.json" onChange={e=>void importBackup(e.target.files?.[0])}/></label></div><div className="warning-note">Automatic background writes to iOS Files are not reliable for a browser/PWA. The app can prepare one-tap exports when opened; a future native wrapper could provide true scheduled backups.</div><div className="danger-zone"><button className="secondary-btn" onClick={()=>{if(confirm('Clear ALL local IndexedDB data? This cannot be undone unless you exported a backup.'))void clearLocalData();}}>Clear IndexedDB & reset app</button></div></section>
 <section className="panel"><div className="panel-header"><div><h2>Device Lock</h2><p>Protect the local app if somebody discovers the public URL.</p></div><Smartphone size={18}/></div>{settings?.lockEnabled?<div className="inline-actions"><span className="sync-state"><span className="status-dot online"/> Lock enabled ({settings.lockMethod})</span><button className="secondary-btn" onClick={()=>void disableLock()}><Unlock size={15}/> Disable lock</button></div>:<><div className="settings-grid"><label>PIN<input inputMode="numeric" type="password" maxLength={8} value={pin} onChange={e=>setPin(e.target.value)} placeholder="4–8 digits"/></label></div><div className="inline-actions"><button className="secondary-btn" disabled={!pin} onClick={()=>void lockPin()}>Enable PIN</button>{webAuthnAvailable()&&<button className="primary-btn" onClick={()=>void lockPasskey()}><ShieldCheck size={15}/> Enable Face ID / passkey</button>}</div><p className="form-help">Face ID uses the iPhone/browser platform authenticator. It requires HTTPS and supported WebAuthn.</p></>}</section>
 <section className="panel"><div className="panel-header"><div><h2>About</h2><p>Expense Tracker · local-first personal finance</p></div><RefreshCcw size={18}/></div><div className="developer-signature">Designed & developed by <strong>A J</strong><span>React · IndexedDB · Google Sheets</span></div></section>
 </div>;
}
