import { useMemo, useState } from 'react';
import { BarChart3, CalendarDays, PieChart as PieIcon } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip, BarChart, Bar, CartesianGrid, XAxis, YAxis } from 'recharts';
import { useAccounts, useCategories, useTransactions } from '../hooks/useDb';
import { formatCurrency } from '../utils/format';
import { startOfMonth, endOfMonth, parseISO } from 'date-fns';

export default function Stats(){
  const transactions=useTransactions(); const categories=useCategories(); const accounts=useAccounts(); const navigate=useNavigate(); const [params,setParams]=useSearchParams();
  const [month,setMonth]=useState(params.get('month') || new Date().toISOString().slice(0,7)); const [category,setCategory]=useState(params.get('category')||''); const [subcategory,setSubcategory]=useState(params.get('subcategory')||''); const [account,setAccount]=useState(params.get('account')||'');
  const roots=useMemo(()=>categories.filter(c=>!c.parentId),[categories]); const subs=useMemo(()=>categories.filter(c=>c.parentId===category),[categories,category]);
  const rows=useMemo(()=>{const [y,m]=month.split('-').map(Number);const start=startOfMonth(new Date(y,m-1,1));const end=endOfMonth(start);return transactions.filter(t=>t.type==='EXPENSE').filter(t=>{const d=parseISO(t.transactionDateTime);return d>=start&&d<=end&&!category||true}).filter(t=>{const d=parseISO(t.transactionDateTime); return d>=start&&d<=end && (!category||t.categoryId===category) && (!subcategory||t.subcategoryId===subcategory) && (!account||t.accountId===account);});},[transactions,month,category,subcategory,account]);
  const byCategory=useMemo(()=>{const map=new Map<string,number>();rows.forEach(t=>map.set(t.categoryId||'uncat',(map.get(t.categoryId||'uncat')||0)+t.amount));return [...map.entries()].sort((a,b)=>b[1]-a[1]).map(([id,amount])=>({id,name:categories.find(c=>c.id===id)?.name||'Uncategorized',amount}));},[rows,categories]);
  const byAccount=useMemo(()=>{const map=new Map<string,number>();rows.forEach(t=>map.set(t.accountId,(map.get(t.accountId)||0)+t.amount));return [...map.entries()].map(([id,amount])=>({name:accounts.find(a=>a.id===id)?.name||'Unknown',amount})).sort((a,b)=>b.amount-a.amount);},[rows,accounts]);
  const update=()=>{const next=new URLSearchParams();next.set('month',month);if(category)next.set('category',category);if(subcategory)next.set('subcategory',subcategory);if(account)next.set('account',account);setParams(next);};
  return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Stats</span><h1>Spending statistics</h1><p className="muted">Filter by month, category, subcategory and account.</p></div></section><div className="toolbar stat-filters"><label className="tool-field"><CalendarDays size={16}/><input type="month" value={month} onChange={e=>{setMonth(e.target.value);}}/></label><select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory('');}}><option value="">All categories</option>{roots.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={subcategory} disabled={!category} onChange={e=>setSubcategory(e.target.value)}><option value="">All subcategories</option>{subs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={account} onChange={e=>setAccount(e.target.value)}><option value="">All accounts</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><button className="secondary-btn" onClick={update}>Apply</button></div><section className="metric-grid"><div className="metric-card"><span>Filtered spend</span><strong>{formatCurrency(rows.reduce((s,t)=>s+t.amount,0))}</strong><small>{rows.length} transactions</small></div><div className="metric-card"><span>Average</span><strong>{formatCurrency(rows.length?rows.reduce((s,t)=>s+t.amount,0)/rows.length:0)}</strong><small>Per transaction</small></div></section><div className="report-grid"><section className="panel"><div className="panel-header"><div><h2>Category spend</h2><p>Tap a category to drill into transactions.</p></div><PieIcon size={18}/></div><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={byCategory} dataKey="amount" nameKey="name" innerRadius="48%" outerRadius="78%" onClick={(entry)=>entry?.id && navigate(`/transactions?month=${month}&category=${entry.id}`)}>{byCategory.map((entry,index)=><Cell key={entry.id} fill={['#7c8cff','#5dd39e','#f2c14e','#e17878','#7fc8f8','#c39be8'][index%6]}/>)}</Pie><Tooltip formatter={(v)=>formatCurrency(Number(v))}/></PieChart></ResponsiveContainer><div className="stacked-list">{byCategory.map(c=><button className="stat-row clickable" key={c.id} onClick={()=>navigate(`/transactions?month=${month}&category=${c.id}`)}><span>{c.name}</span><strong>{formatCurrency(c.amount)}</strong></button>)}</div></section><section className="panel"><div className="panel-header"><div><h2>By account</h2><p>Filtered current-month spending.</p></div><BarChart3 size={18}/></div><ResponsiveContainer width="100%" height={300}><BarChart data={byAccount} layout="vertical"><CartesianGrid stroke="#252a32" horizontal={false}/><XAxis type="number" stroke="#78808e"/><YAxis type="category" dataKey="name" width={100} stroke="#78808e"/><Tooltip formatter={(v)=>formatCurrency(Number(v))}/><Bar dataKey="amount" fill="#7c8cff" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></section></div></div>;
}
