import { useMemo, useState } from 'react';
import { CalendarDays, Search, SlidersHorizontal, X } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { startOfMonth, endOfMonth, parseISO } from 'date-fns';
import { useAccounts, useCategories, useTransactions } from '../hooks/useDb';
import TransactionList from '../components/TransactionList';
import { formatCurrency } from '../utils/format';

export default function Transactions(){
  const navigate=useNavigate(); const txns=useTransactions(); const accounts=useAccounts(); const categories=useCategories(); const [params]=useSearchParams();
  const [month,setMonth]=useState(params.get('month') || new Date().toISOString().slice(0,7)); const [view,setView]=useState(params.get('view')||'All Transactions'); const [query,setQuery]=useState(''); const [category,setCategory]=useState(params.get('category')||''); const [subcategory,setSubcategory]=useState(params.get('subcategory')||''); const [account,setAccount]=useState(params.get('account')||'');
  const roots=useMemo(()=>categories.filter(c=>!c.parentId),[categories]); const subs=useMemo(()=>categories.filter(c=>c.parentId===category),[categories,category]);
  const filtered=useMemo(()=>{const [y,m]=month.split('-').map(Number);const start=startOfMonth(new Date(y,m-1,1));const end=endOfMonth(start);const seen=new Set<string>();let rows=txns.filter(t=>{if(seen.has(t.id))return false;seen.add(t.id);const d=parseISO(t.transactionDateTime);return d>=start&&d<=end}).filter(t=>{const d=parseISO(t.transactionDateTime);return d>=start&&d<=end&&(!category||t.categoryId===category)&&(!subcategory||t.subcategoryId===subcategory)&&(!account||t.accountId===account)&&(!query.trim()||`${t.merchant||''} ${t.notes||''}`.toLowerCase().includes(query.toLowerCase()))}).filter(t=>view==='All Transactions'||(view==='Expenses'&&t.type==='EXPENSE')||(view==='Income'&&t.type==='INCOME')||(view==='Recurring'&&t.source==='RECURRING'));return rows;},[txns,month,view,query,category,subcategory,account]);
  const expenseTotal=filtered.filter(t=>t.type==='EXPENSE').reduce((s,t)=>s+t.amount,0);
  const clearFilters=()=>{setCategory('');setSubcategory('');setAccount('');setQuery('');setView('All Transactions');};
  return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Ledger</span><h1>Transactions</h1><p className="muted">Current full month by default. Use filters for category and account drill-downs.</p></div><button className="secondary-btn" onClick={()=>navigate('/stats')}><SlidersHorizontal size={16}/> Open Stats</button></section>
    <div className="toolbar"><label className="tool-field"><CalendarDays size={16}/><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><select value={view} onChange={e=>setView(e.target.value)}><option>All Transactions</option><option>Expenses</option><option>Income</option><option>Recurring</option></select><label className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search merchant or note"/></label><select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory('')}}><option value="">All categories</option>{roots.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={subcategory} disabled={!category} onChange={e=>setSubcategory(e.target.value)}><option value="">All subcategories</option>{subs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={account} onChange={e=>setAccount(e.target.value)}><option value="">All accounts</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div>
    {(category||subcategory||account||query||view!=='All Transactions')&&<div className="filter-chips"><button onClick={clearFilters}>Clear filters <X size={13}/></button>{category&&<span>{roots.find(c=>c.id===category)?.name}</span>}{subcategory&&<span>{subs.find(c=>c.id===subcategory)?.name}</span>}{account&&<span>{accounts.find(a=>a.id===account)?.name}</span>}</div>}
    <div className="summary-strip"><span>{filtered.length} transactions</span><strong>{formatCurrency(expenseTotal)} expenses</strong></div><section className="panel"><TransactionList transactions={filtered} accounts={accounts} categories={categories} onSelect={t=>navigate(`/transactions/${t.id}`)}/></section>
  </div>;
}
