import { useNavigate } from 'react-router-dom';
import { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Search, SlidersHorizontal, X } from 'lucide-react';

import { addMonths, endOfMonth, format, startOfMonth } from 'date-fns';
import { useAccounts, useCategories, useTransactions } from '../hooks/useDb';
import { formatCurrency } from '../utils/format';
import { deleteTransaction } from '../services/transactionService';
export default function Transactions(){
 const navigate=useNavigate(),tx=useTransactions()??[],accounts=useAccounts()??[],categories=useCategories()??[]; const [month,setMonth]=useState(new Date());const [view,setView]=useState('All Transactions');const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [subcategory,setSubcategory]=useState('');const [account,setAccount]=useState('');const [filtersOpen,setFiltersOpen]=useState(false);
 const roots=categories.filter(c=>!c.parentId),subs=categories.filter(c=>c.parentId===category);
 const filtered=useMemo(()=>{const start=startOfMonth(month),end=endOfMonth(month);return tx.filter(t=>{const d=new Date(t.transactionDateTime);if(d<start||d>end)return false;if(view==='Expenses'&&t.type!=='EXPENSE')return false;if(view==='Income'&&t.type!=='INCOME')return false;if(view==='Investments'&&t.type!=='INVESTMENT')return false;if(view==='Recurring'&&t.source!=='RECURRING')return false;if(category&&t.categoryId!==category)return false;if(subcategory&&t.subcategoryId!==subcategory)return false;if(account&&t.accountId!==account)return false;return !query.trim()||`${t.merchant||''} ${t.notes||''}`.toLowerCase().includes(query.toLowerCase());}).sort((a,b)=>+new Date(b.transactionDateTime)-+new Date(a.transactionDateTime));},[tx,month,view,query,category,subcategory,account]);
 const groups=useMemo(()=>{const m=new Map<string,typeof filtered>();filtered.forEach(t=>{const k=format(new Date(t.transactionDateTime),'yyyy-MM-dd');const arr=m.get(k)||[];arr.push(t);m.set(k,arr);});return [...m.entries()];},[filtered]);
 const clear=()=>{setView('All Transactions');setQuery('');setCategory('');setSubcategory('');setAccount('');};
 const shift=(n:number)=>setMonth(m=>addMonths(m,n));
 return <div className="page-stack"><section className="hero-row"><div><span className="eyebrow">Ledger</span><h1>Transactions</h1><p className="muted">Current month by default.</p></div></section>
 <div className="month-nav"><button className="icon-btn" onClick={()=>shift(-1)}><ChevronLeft/></button><strong>{format(month,'MMMM yyyy')}</strong><button className="icon-btn" onClick={()=>shift(1)}><ChevronRight/></button></div>
 <section className="panel filter-panel"><button className="filter-toggle" onClick={()=>setFiltersOpen(v=>!v)}><span><SlidersHorizontal size={15}/> Filters {category||subcategory||account||query||view!=='All Transactions'?'· active':''}</span><span>{filtersOpen?'Hide':'Show'}</span></button>{filtersOpen&&<div className="stats-filter-body"><div className="toolbar"><select value={view} onChange={e=>setView(e.target.value)}><option>All Transactions</option><option>Expenses</option><option>Income</option><option>Investments</option><option>Recurring</option></select><label className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search merchant or note"/></label><select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory('')}}><option value="">All categories</option>{roots.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={subcategory} disabled={!category} onChange={e=>setSubcategory(e.target.value)}><option value="">All subcategories</option>{subs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={account} onChange={e=>setAccount(e.target.value)}><option value="">All accounts</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><button className="secondary-btn" onClick={clear}><X size={14}/> Clear filters</button></div>}</section>
 <div className="summary-strip"><span>{filtered.length} transactions</span><strong>{formatCurrency(filtered.filter(t=>t.type==='EXPENSE').reduce((s,t)=>s+t.amount,0))} expenses</strong></div>
 <section className="panel grouped-transactions">{groups.length===0?<div className="empty-state"><h3>No transactions</h3><p>Try another month or clear the filters.</p></div>:groups.map(([date,rows])=><div className="date-group" key={date}><div className="date-group-head"><strong>{new Date(`${date}T12:00:00`).toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'short'})}</strong><span>{formatCurrency(rows.reduce((s,t)=>s+(t.type==='EXPENSE'?-t.amount:t.type==='INCOME'?t.amount:0),0))}</span></div>{rows.map(t=><div className="transaction-row" key={t.id} onClick={()=>navigate(`/transactions/${t.id}`)}><div className="transaction-main"><strong>{t.merchant||categories.find(c=>c.id===t.categoryId)?.name||t.type}</strong><span>{categories.find(c=>c.id===t.subcategoryId)?.name||categories.find(c=>c.id===t.categoryId)?.name||'Uncategorized'} · {accounts.find(a=>a.id===t.accountId)?.name||'Account'}</span></div><div className="transaction-meta"><time>{new Date(t.transactionDateTime).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</time><strong className={t.type==='INCOME'?'positive':t.type==='INVESTMENT'?'investment-text':'negative'}>{t.type==='EXPENSE'?'-':t.type==='INCOME'?'+':''}{formatCurrency(t.amount)}</strong>{t.source==='RECURRING'&&<span className="auto-badge">Auto</span>}</div></div>)}</div>)}</section>
 </div>;
}
