import { RefreshCcw, Zap } from 'lucide-react';
import { formatCurrency } from '../utils/format';
import type { Account, Category, Transaction } from '../types/models';
interface Props { transactions: Transaction[]; accounts: Account[]; categories: Category[]; onSelect?: (transaction: Transaction) => void; }
export default function TransactionList({transactions,accounts,categories,onSelect}:Props){
  const accountMap=new Map(accounts.map(a=>[a.id,a.name]));const categoryMap=new Map(categories.map(c=>[c.id,c]));
  const unique=transactions.filter((t,i,arr)=>arr.findIndex(x=>x.id===t.id)===i);
  if(!unique.length)return <div className="empty-state"><div className="empty-icon">₹</div><h3>No transactions here</h3><p>Add your first transaction to start tracking spending.</p></div>;
  const groups=unique.slice().sort((a,b)=>+new Date(b.transactionDateTime)-+new Date(a.transactionDateTime)).reduce<Record<string,Transaction[]>>((acc,t)=>{const key=new Date(t.transactionDateTime).toLocaleDateString('en-IN',{day:'numeric',month:'short'});(acc[key]??=[]).push(t);return acc;},{});
  return <div className="transaction-list">{Object.entries(groups).map(([day,items])=>{const dailyExpenses=items.filter(t=>t.type==='EXPENSE').reduce((sum,t)=>sum+t.amount,0);const dailyIncome=items.filter(t=>t.type==='INCOME').reduce((sum,t)=>sum+t.amount,0);return <section key={day} className="day-group"><div className="day-label"><span>{day}</span><span>{dailyExpenses?`Spent ${formatCurrency(dailyExpenses)}`:''}{dailyIncome?`${dailyExpenses?' · ':''}Income ${formatCurrency(dailyIncome)}`:''}</span></div>{items.map(t=>{const cat=categoryMap.get(t.categoryId||'');const sub=categoryMap.get(t.subcategoryId||'');const sign=t.type==='INCOME'?'+':'-';const icon=t.source==='RECURRING'?<RefreshCcw size={13}/>:t.source==='AUTOMATION'?<Zap size={13}/>:null;return <button key={t.id} className="transaction-row" onClick={()=>onSelect?.(t)}><div className="transaction-main"><strong>{t.merchant||sub?.name||cat?.name||'Transaction'}</strong><span>{sub?.name ? `${cat?.name||'Category'} · ${sub.name}` : (cat?.name||'Uncategorized')} · {accountMap.get(t.accountId)||'Unknown account'}</span></div><div className="transaction-meta"><time>{new Date(t.transactionDateTime).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}</time><strong className={t.type==='INCOME'?'positive':''}>{sign}{formatCurrency(t.amount)}</strong>{icon&&<span className="source-icon" title={t.source==='RECURRING'?'Recurring payment':'Imported automatically'}>{icon}</span>}</div></button>})}</section>})}</div>;
}
