/**
 * Expense Tracker Google Apps Script API.
 *
 * Google Sheets is a reporting/backup copy. IndexedDB is the local source of truth.
 * Keep SHEET_ID and SYNC_TOKEN private inside Apps Script.
 */
const CONFIG={SHEET_ID:'REPLACE_ME',SYNC_TOKEN:'REPLACE_ME'};
function doGet(e){try{authenticate(e);const action=(e?.parameter?.action)||'HEALTH';if(action==='RESTORE_ALL')return json(restoreAll());return json({success:true,service:'expense-tracker',time:new Date().toISOString()});}catch(err){return json({success:false,message:String(err)})}}
function doPost(e){try{authenticate(e);const body=JSON.parse(e?.postData?.contents||'{}');if(body.action==='BATCH_SYNC')return json(batchSync(body.changes||[]));if(body.action==='RESTORE_ALL')return json(restoreAll());return json({success:false,message:'Unknown action'});}catch(err){return json({success:false,message:String(err)})}}
function authenticate(e){if(CONFIG.SYNC_TOKEN==='REPLACE_ME')return;const token=e?.parameter?.token||'';const header=e?.headers?.Authorization||'';if(token!==CONFIG.SYNC_TOKEN&&header!=='Bearer '+CONFIG.SYNC_TOKEN)throw new Error('Unauthorized');}
function batchSync(changes){const ss=SpreadsheetApp.openById(CONFIG.SHEET_ID);let processed=0,failed=0,errors=[];changes.forEach(c=>{try{const entity=String(c.entityType||'');const row=c.payload||{};const id=String(c.entityId||row.id||'');if(!id)throw new Error('Missing entity ID');const config=entityConfig(entity);if(!config)return; if(c.operation==='DELETE'){deleteEntity(ss,config.sheet,config.headers,id);}else{upsertEntity(ss,config.sheet,config.headers,row);}processed++;}catch(err){failed++;errors.push(String(err))}});return{success:failed===0,processed,failed,errors};}
function entityConfig(entity){const map={TRANSACTION:{sheet:'Transactions',headers:transactionHeaders()},CATEGORY:{sheet:'Categories',headers:categoryHeaders()},ACCOUNT:{sheet:'Accounts',headers:accountHeaders()},RECURRING_RULE:{sheet:'RecurringRules',headers:recurringHeaders()},BUDGET:{sheet:'Budgets',headers:budgetHeaders()},INVESTMENT:{sheet:'Investments',headers:investmentHeaders()},INTEREST_ACCOUNT:{sheet:'InterestAccounts',headers:interestHeaders()},PROJECTED_INCOME:{sheet:'ProjectedIncome',headers:projectedHeaders()},SAVED_REPORT:{sheet:'SavedReports',headers:savedReportHeaders()}};return map[entity]||null;}
function upsertEntity(ss,sheetName,headers,row){const sheet=getOrCreateSheet(ss,sheetName,headers);const id=String(row.id||'');if(!id)throw new Error(sheetName+': missing id');const map=existingRowMap(sheet),values=headers.map(h=>row[h]==null?'':row[h]);if(map[id])sheet.getRange(map[id],1,1,values.length).setValues([values]);else sheet.appendRow(values);}
function deleteEntity(ss,sheetName,headers,id){const sheet=ss.getSheetByName(sheetName);if(!sheet||sheet.getLastRow()<2)return;const map=existingRowMap(sheet);if(map[id])sheet.deleteRow(map[id]);}
function restoreAll(){const ss=SpreadsheetApp.openById(CONFIG.SHEET_ID);return{success:true,transactions:sheetObjects(ss.getSheetByName('Transactions'),transactionHeaders()),accounts:sheetObjects(ss.getSheetByName('Accounts'),accountHeaders()),categories:sheetObjects(ss.getSheetByName('Categories'),categoryHeaders()),recurringRules:sheetObjects(ss.getSheetByName('RecurringRules'),recurringHeaders()),budgets:sheetObjects(ss.getSheetByName('Budgets'),budgetHeaders()),investments:sheetObjects(ss.getSheetByName('Investments'),investmentHeaders()),interestAccounts:sheetObjects(ss.getSheetByName('InterestAccounts'),interestHeaders()),projectedIncomeEvents:sheetObjects(ss.getSheetByName('ProjectedIncome'),projectedHeaders()),savedReports:sheetObjects(ss.getSheetByName('SavedReports'),savedReportHeaders())};}
function sheetObjects(sheet,headers){if(!sheet||sheet.getLastRow()<2)return[];const rows=sheet.getRange(2,1,sheet.getLastRow()-1,headers.length).getValues();return rows.filter(r=>r[0]!=='').map(r=>{const o={};headers.forEach((h,i)=>o[h]=r[i]);return o;});}
function existingRowMap(sheet){const map={};const last=sheet.getLastRow();if(last<2)return map;sheet.getRange(2,1,last-1,1).getValues().flat().forEach((id,i)=>{if(id!=='')map[String(id)]=i+2});return map;}
function transactionHeaders(){return['id','transactionDateTime','type','amount','accountId','categoryId','subcategoryId','merchant','notes','source','recurringRuleId','sourceId','createdAt','updatedAt','deletedAt','syncStatus'];}
function categoryHeaders(){return['id','name','parentId','icon','defaultNeedWant','defaultEssentialDiscretionary','defaultFixedVariable','active','sortOrder','createdAt','updatedAt'];}
function accountHeaders(){return['id','name','type','institution','lastFourDigits','isDefault','active','createdAt','updatedAt'];}
function recurringHeaders(){return['id','name','amount','type','accountId','categoryId','subcategoryId','merchant','notes','frequency','dayOfMonth','startDate','endDate','active','lastGeneratedDate','nextDueDate','createdAt','updatedAt'];}
function budgetHeaders(){return['id','categoryId','amount','period','startDate','endDate','createdAt','updatedAt'];}
function investmentHeaders(){return['id','date','name','assetType','type','amount','accountId','notes','createdAt','updatedAt','syncStatus','transactionId'];}
function interestHeaders(){return['id','name','institution','type','principal','recurringAmount','interestRate','compounding','openingDate','maturityDate','maturityMonths','payoutFrequency','accountId','active','autoRecordInterest','notes','createdAt','updatedAt'];}
function projectedHeaders(){return['id','interestAccountId','expectedDate','amount','categoryId','status','transactionId','createdAt','updatedAt'];}
function savedReportHeaders(){return['id','name','categoryIds','subcategoryIds','accountIds','transactionTypes','createdAt','updatedAt'];}
function getOrCreateSheet(ss,name,headers){let s=ss.getSheetByName(name);if(!s)s=ss.insertSheet(name);if(s.getLastRow()===0)s.appendRow(headers);return s;}
function json(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);}
