// -----------------------------------------------------------------------------
// MANAGEMENT / SETTINGS
// -----------------------------------------------------------------------------
// This screen lets you change the master data that V1 required editing in
// Google Sheets. Every save writes directly to the corresponding Sheet tab.

import { useEffect, useState, type ReactNode } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../api/client';
import { useAccounts, useCategories } from '../categories/useCategories';

const today = () => new Date().toISOString().slice(0, 10);
const blank = (value = '') => value;

export function Manage() {
  const [tab, setTab] = useState('Categories');
  const tabs = ['Categories', 'Accounts', 'Budgets', 'Recurring', 'Subscriptions', 'Goals', 'Investments', 'Assets', 'Liabilities', 'Merchants', 'Settings'];
  return <div className="space-y-4"><div className="chip-scroll">{tabs.map(t => <button key={t} onClick={() => setTab(t)} className={tab === t ? 'chip active' : 'chip'}>{t}</button>)}</div>
    {tab === 'Categories' && <CategoryEditor />}{tab === 'Accounts' && <AccountsEditor />}{tab === 'Budgets' && <BudgetsEditor />}{tab === 'Recurring' && <RecurringEditor />}{tab === 'Subscriptions' && <SubscriptionsEditor />}{tab === 'Goals' && <GoalsEditor />}{tab === 'Investments' && <InvestmentsEditor />}{tab === 'Assets' && <AssetsEditor />}{tab === 'Liabilities' && <LiabilitiesEditor />}{tab === 'Merchants' && <MerchantsEditor />}{tab === 'Settings' && <SettingsEditor />}
  </div>;
}

function CategoryEditor() {
  const qc = useQueryClient(); const { data: categories = [] } = useCategories();
  const [name, setName] = useState(''); const [nature, setNature] = useState('EXPENSE'); const [selected, setSelected] = useState(''); const [sub, setSub] = useState('');
  const saveCategory = async () => { if (!name.trim()) return; await api.saveCategory({ displayName: name.trim(), nature: nature as any, active: true }); setName(''); qc.invalidateQueries({ queryKey: ['categories'] }); };
  const saveSub = async () => { if (!sub.trim() || !selected) return; await api.saveSubcategory({ categoryId: selected, displayName: sub.trim(), active: true }); setSub(''); qc.invalidateQueries({ queryKey: ['categories'] }); };
  return <section className="card"><h3>Categories & subcategories</h3><p className="muted">Names are labels. Stable IDs protect your old transactions when you rename them.</p><div className="compact-grid"><Field label="New category"><input className="input" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Pets" /></Field><Field label="Nature"><select className="input" value={nature} onChange={e => setNature(e.target.value)}><option>EXPENSE</option><option>INCOME</option><option>INVESTMENT</option></select></Field></div><button className="primary-button" onClick={saveCategory}>Add category</button><hr />
    <div className="compact-grid"><Field label="Category"><select className="input" value={selected} onChange={e => setSelected(e.target.value)}><option value="">Select</option>{categories.map(c => <option key={c.categoryId} value={c.categoryId}>{c.displayName}</option>)}</select></Field><Field label="New subcategory"><input className="input" value={sub} onChange={e => setSub(e.target.value)} placeholder="e.g. Vet" /></Field></div><button className="secondary-button" onClick={saveSub}>Add subcategory</button>
    <div className="list">{categories.map(c => <div key={c.categoryId}><strong>{c.displayName}</strong><small>{c.subcategories.map(s => s.displayName).join(' · ')}</small></div>)}</div></section>;
}

function AccountsEditor() { const qc = useQueryClient(); const { data: accounts = [] } = useAccounts(); const [name, setName] = useState(''); const [type, setType] = useState('BANK'); const [balance, setBalance] = useState('0'); const save = async () => { if (!name) return; await api.saveAccount({ displayName: name, type, openingBalance: Number(balance), currency: 'INR', active: true }); setName(''); qc.invalidateQueries({ queryKey: ['accounts'] }); }; return <Editor title="Accounts" fields={<><Field label="Account name"><input className="input" value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Type"><select className="input" value={type} onChange={e => setType(e.target.value)}><option>BANK</option><option>CASH</option><option>CREDIT_CARD</option><option>WALLET</option><option>INVESTMENT</option><option>OTHER</option></select></Field><Field label="Opening balance"><input className="input" type="number" value={balance} onChange={e => setBalance(e.target.value)} /></Field></>} onSave={save} list={accounts.map(a => `${a.displayName} · ${a.type} · ₹${Number(a.openingBalance || 0).toLocaleString('en-IN')}`)} />; }

function BudgetsEditor() { const qc = useQueryClient(); const { data: categories = [] } = useCategories(); const { data = [] } = useQuery({ queryKey: ['budgets'], queryFn: api.getBudgets }); const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [categoryId, setCategoryId] = useState(''); const [amount, setAmount] = useState(''); const save = async () => { if (!categoryId || !amount) return; await api.saveBudget({ month, categoryId, amount: Number(amount), active: true }); setAmount(''); qc.invalidateQueries({ queryKey: ['budgets'] }); }; return <Editor title="Budgets" fields={<><Field label="Month"><input className="input" type="month" value={month} onChange={e => setMonth(e.target.value)} /></Field><Field label="Category"><select className="input" value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">Select</option>{categories.filter(c => c.nature === 'EXPENSE').map(c => <option key={c.categoryId} value={c.categoryId}>{c.displayName}</option>)}</select></Field><Field label="Budget amount"><input className="input" type="number" value={amount} onChange={e => setAmount(e.target.value)} /></Field></>} onSave={save} list={data.map(x => `${x.month} · ${x.categoryId} · ₹${Number(x.amount).toLocaleString('en-IN')}`)} />; }

function RecurringEditor() { const qc = useQueryClient(); const { data: categories = [] } = useCategories(); const { data: accounts = [] } = useAccounts(); const { data = [] } = useQuery({ queryKey: ['recurring'], queryFn: api.getRecurring }); const [name, setName] = useState(''); const [amount, setAmount] = useState(''); const [date, setDate] = useState(today()); const [cat, setCat] = useState(''); const [account, setAccount] = useState(''); const save = async () => { if (!name || !amount || !cat || !account) return; await api.saveRecurring({ displayName: name, amount: Number(amount), frequency: 'MONTHLY', nextDueDate: date, categoryId: cat, accountId: account, active: true }); setName(''); qc.invalidateQueries({ queryKey: ['recurring'] }); }; return <Editor title="Recurring expenses" fields={<><Field label="Name"><input className="input" value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Amount"><input className="input" type="number" value={amount} onChange={e => setAmount(e.target.value)} /></Field><Field label="Next due"><input className="input" type="date" value={date} onChange={e => setDate(e.target.value)} /></Field><SelectField label="Category" value={cat} setValue={setCat} options={categories.filter(c => c.nature === 'EXPENSE').map(c => [c.categoryId, c.displayName])} /><SelectField label="Account" value={account} setValue={setAccount} options={accounts.map(a => [a.accountId, a.displayName])} /></>} onSave={save} list={data.map(x => `${x.displayName} · ₹${x.amount} · ${x.frequency} · next ${x.nextDueDate}`)} />; }

function SubscriptionsEditor() { const qc = useQueryClient(); const { data: categories = [] } = useCategories(); const { data: accounts = [] } = useAccounts(); const { data = [] } = useQuery({ queryKey: ['subscriptions'], queryFn: api.getSubscriptions }); const [name, setName] = useState(''); const [amount, setAmount] = useState(''); const [date, setDate] = useState(today()); const [cat, setCat] = useState(''); const [account, setAccount] = useState(''); const save = async () => { if (!name || !amount || !cat || !account) return; await api.saveSubscription({ displayName: name, amount: Number(amount), billingCycle: 'MONTHLY', nextBillingDate: date, categoryId: cat, accountId: account, active: true }); setName(''); qc.invalidateQueries({ queryKey: ['subscriptions'] }); }; return <Editor title="Subscriptions" fields={<><Field label="Service"><input className="input" value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Amount"><input className="input" type="number" value={amount} onChange={e => setAmount(e.target.value)} /></Field><Field label="Next billing"><input className="input" type="date" value={date} onChange={e => setDate(e.target.value)} /></Field><SelectField label="Category" value={cat} setValue={setCat} options={categories.map(c => [c.categoryId, c.displayName])} /><SelectField label="Account" value={account} setValue={setAccount} options={accounts.map(a => [a.accountId, a.displayName])} /></>} onSave={save} list={data.map(x => `${x.displayName} · ₹${x.amount} · ${x.billingCycle} · next ${x.nextBillingDate}`)} />; }

function GoalsEditor() { const qc = useQueryClient(); const { data = [] } = useQuery({ queryKey: ['goals'], queryFn: api.getGoals }); const [name, setName] = useState(''); const [target, setTarget] = useState(''); const [current, setCurrent] = useState('0'); const [date, setDate] = useState(''); const save = async () => { if (!name || !target) return; await api.saveGoal({ name, targetAmount: Number(target), currentAmount: Number(current), targetDate: date, priority: 'MEDIUM', active: true }); setName(''); qc.invalidateQueries({ queryKey: ['goals'] }); }; return <Editor title="Goals" fields={<><Field label="Goal"><input className="input" value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Target amount"><input className="input" type="number" value={target} onChange={e => setTarget(e.target.value)} /></Field><Field label="Current amount"><input className="input" type="number" value={current} onChange={e => setCurrent(e.target.value)} /></Field><Field label="Target date"><input className="input" type="date" value={date} onChange={e => setDate(e.target.value)} /></Field></>} onSave={save} list={data.map(x => `${x.name} · ₹${x.currentAmount}/${x.targetAmount} · ${x.targetDate || 'no date'}`)} />; }

function InvestmentsEditor() { const qc = useQueryClient(); const { data: accounts = [] } = useAccounts(); const { data = [] } = useQuery({ queryKey: ['investments'], queryFn: api.getInvestments }); const [name, setName] = useState(''); const [type, setType] = useState('MUTUAL_FUND'); const [value, setValue] = useState(''); const [account, setAccount] = useState(''); const save = async () => { if (!name || !value || !account) return; await api.saveInvestment({ date: today(), investmentType: type, name, currentValue: Number(value), accountId: account, active: true }); setName(''); qc.invalidateQueries({ queryKey: ['investments'] }); qc.invalidateQueries({ queryKey: ['netWorth'] }); }; return <Editor title="Investments detail" fields={<><Field label="Investment name"><input className="input" value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Type"><select className="input" value={type} onChange={e => setType(e.target.value)}><option>MUTUAL_FUND</option><option>STOCK</option><option>FD</option><option>GOLD</option><option>PF</option><option>OTHER</option></select></Field><Field label="Current value"><input className="input" type="number" value={value} onChange={e => setValue(e.target.value)} /></Field><SelectField label="Account" value={account} setValue={setAccount} options={accounts.map(a => [a.accountId, a.displayName])} /></>} onSave={save} list={data.map(x => `${x.name} · ${x.investmentType} · ₹${x.currentValue}`)} />; }

function AssetsEditor() { const qc = useQueryClient(); const { data = [] } = useQuery({ queryKey: ['assets'], queryFn: api.getAssets }); const [name, setName] = useState(''); const [value, setValue] = useState(''); const save = async () => { if (!name || !value) return; await api.saveAsset({ name, assetType: 'OTHER', value: Number(value), valuationDate: today(), active: true }); setName(''); qc.invalidateQueries({ queryKey: ['assets'] }); qc.invalidateQueries({ queryKey: ['netWorth'] }); }; return <Editor title="Assets" fields={<><Field label="Asset"><input className="input" value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Value"><input className="input" type="number" value={value} onChange={e => setValue(e.target.value)} /></Field></>} onSave={save} list={data.map(x => `${x.name} · ₹${x.value}`)} />; }

function LiabilitiesEditor() { const qc = useQueryClient(); const { data = [] } = useQuery({ queryKey: ['liabilities'], queryFn: api.getLiabilities }); const [name, setName] = useState(''); const [value, setValue] = useState(''); const save = async () => { if (!name || !value) return; await api.saveLiability({ name, liabilityType: 'OTHER', outstanding: Number(value), valuationDate: today(), active: true }); setName(''); qc.invalidateQueries({ queryKey: ['liabilities'] }); qc.invalidateQueries({ queryKey: ['netWorth'] }); }; return <Editor title="Liabilities" fields={<><Field label="Liability"><input className="input" value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Outstanding"><input className="input" type="number" value={value} onChange={e => setValue(e.target.value)} /></Field></>} onSave={save} list={data.map(x => `${x.name} · ₹${x.outstanding}`)} />; }

function MerchantsEditor() { const qc = useQueryClient(); const { data = [] } = useQuery({ queryKey: ['merchants'], queryFn: api.getMerchants }); const [name, setName] = useState(''); const save = async () => { if (!name) return; await api.saveMerchant({ displayName: name, active: true }); setName(''); qc.invalidateQueries({ queryKey: ['merchants'] }); }; return <Editor title="Merchant management" fields={<Field label="Merchant"><input className="input" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Amazon" /></Field>} onSave={save} list={data.map(x => x.displayName)} />; }

function SettingsEditor() { const qc = useQueryClient(); const { data = {} } = useQuery({ queryKey: ['settings'], queryFn: api.getSettings }); const [currency, setCurrency] = useState('INR'); useEffect(() => setCurrency(data.currency || 'INR'), [data.currency]); const save = async () => { await api.saveSetting({ settingKey: 'currency', settingValue: currency, description: 'Default application currency.' }); qc.invalidateQueries({ queryKey: ['settings'] }); }; return <Editor title="Application settings" fields={<><Field label="Default currency"><input className="input" value={currency} onChange={e => setCurrency(e.target.value.toUpperCase())} /></Field><p className="muted">For category/account customization, use Categories and Accounts tabs. Changes are stored in the corresponding Sheet and automatically loaded by the app.</p></>} onSave={save} list={Object.entries(data).map(([k, v]) => `${k} = ${v}`)} />; }

function Editor({ title, fields, onSave, list }: { title: string; fields: ReactNode; onSave: () => void; list: string[] }) { return <section className="card"><h3>{title}</h3><div className="compact-grid">{fields}</div><button className="primary-button" onClick={onSave}>Save</button><div className="list">{list.map((x, i) => <div key={i}>{x}</div>)}</div></section>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function SelectField({ label, value, setValue, options }: { label: string; value: string; setValue: (v: string) => void; options: string[][] }) { return <Field label={label}><select className="input" value={value} onChange={e => setValue(e.target.value)}><option value="">Select</option>{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></Field>; }
